### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by kjmkznr**
Add documentation that generated by [tfplugindocs](https://github.com/hashicorp/terraform-plugin-docs/tree/main/cmd/tfplugindocs).

### How to update documentation

```
$ go generate ./...
```

### CODE REVIEW

**Comment by heleeen** [comment]
@kjmkznr 

Thank you for the PR! My apologies for the delay in replying to you.

I have checked the documentation format of other terraform providers, there are many providers which use these sections in [Provider Documentation - Terraform by HashiCorp](https://www.terraform.io/docs/registry/providers/docs.html#headers).  
Therefore, I suggest that you add templates of this format like this [terraform-provider-unifi/index.md.tmpl at main · paultyng/terraform-provider-unifi](https://github.com/paultyng/terraform-provider-unifi/blob/main/templates/index.md.tmpl).

**Comment by kjmkznr** [comment]
Thanks comment!

I added templates/indexmd.tmpl file and update docs.

**Comment by heleeen** [comment]
Thank you for adding template for index!
I would appreciate it if you could add templates for resources and data sources.

**Comment by kjmkznr** [comment]
I add each resource and data-source templates.

Please review subcategories.

**Comment by heleeen** [comment]
Thank you for adding templates for resources and data sources!
I’m sorry to bother you again. 

How about removing the subcategories from .tmpl files to keep it simple?
And, how about using Headers which is recommended in Terraform Providers Docmentation (https://www.terraform.io/docs/registry/providers/docs.html#headers).

I reviewed the subcategories, maybe it is good idea to divide roles from service.

**Comment by kjmkznr** [comment]
> And, how about using Headers which is recommended in Terraform Providers Docmentation (https://www.terraform.io/docs/registry/providers/docs.html#headers).

Sorry,
I didn't know what to do specifically.
Is it means that the header should look like following?

My Pull Request:
```
# <resource name> (Resource)
## Example Usage
## Schema
### Required
### Optional
## Import
```

Terraform Providers Documentations:
````
# <resource name> Resource/Data Source
## Example Usage
## Argument Reference
## Attribute Reference
````

**Comment by heleeen** [comment]
Thanks for checking my comment and I'm sorry for my lack of explanation.
It’s exactly as you said.
I mean the headers as shown below.

Index Headers(https://www.terraform.io/docs/registry/providers/docs.html#index-headers)

````
# <provider> Provider

Summary of what the provider is for, including use cases and links to
app/service documentation.

## Example Usage

```hcl
 // Code block with an example of how to use this provider.
```

## Argument Reference

* List any arguments for the provider block.

````

Resource/Data Source Headers(https://www.terraform.io/docs/registry/providers/docs.html#resource-data-source-headers)

````
# <resource name> Resource/Data Source

Description of what this resource does, with links to official
app/service documentation.

## Example Usage

 ```hcl
// Code block with an example of how to use this resource.
 ```

## Argument Reference

* `attribute_name` - (Optional/Required) List arguments this resource takes.

## Attribute Reference

* `attribute_name` - List attributes that this resource exports.
````

**Comment by kjmkznr** [comment]
Thanks you comment.
I understood you said.

tfplugindocs does not support 'Terraform Providers Documentation' format.
tfplugindocs template does not separate arguments and attributes.
https://github.com/hashicorp/terraform-plugin-docs/blob/main/internal/provider/template.go#L186-L199

When using 'Terraform Provider Documentation', I think it is better to manage docs without using tfplugindocs and templates.

**Comment by kjmkznr** [comment]
Thank you review.

If do not use tfplugindocs, I close this PR as it departs from the original purpose.
I don't know the image of the output of the document, could you please create an early document?

**Comment by heleeen** [comment]
I appreciate your reply.

We'll prepare a PR of a base for the documentation.

**Pull request closed without merging**
