### PR TITLE
update readme 

### PR DESCRIPTION
**Pull request by heleeen**
- update github action's badge
- add usage sample to prepare registration, requirements, acknowledgements
- fix path for package

### CODE REVIEW

**Comment by nanotubekanitake** [comment]
@xcezx 
Can you please add a license notation for @xcezx as the copyright holder?

**Review by nanotubekanitake — APPROVED** [review]

**Review by hayajo — APPROVED** [review]
LGTM!

**Review by tatsuru — APPROVED** [review]
👍

**Comment by heleeen** [comment]
Thank you for adding copyright and your review!

**Pull request merged**
