### PR TITLE
Add mackerel_service_metric_names data source.

### PR DESCRIPTION
**Pull request by fujiwara**
Hi.  I add mackerel_service_metric_names data source.

### motivation

I hope to set some monitors to available service metrics.
But these service metrics may be expanded by on demand.

So I want to get the service metric names from data resources.

For example,

```tf
data "mackerel_service_metric_names" "example-resources" {
  name   = "Example"
  prefix = "custom.example."
}

resource "mackerel_monitor" "example-resources-under-100" {
  for_each = data.mackerel_service_metric_names.example-resources
  name     = each.key

  service_metric {
    service                  = "Example"
    metric                   = each.value
    operator                 = "<"
    duration                 = 1
    warning                  = 100
  }
}
```

### CODE REVIEW

**Comment by hayajo** [comment]
Hi, @fujiwara !

Thanks for your contribution 🤝
The code looks good to me and it works well.

Please add a documentation if you can.

**Comment by fujiwara** [comment]
@hayajo Thank you for reviewing! Added a document file 542e6f1.

**Comment by hayajo** [comment]
@fujiwara 
Thanks for adding the documentation!

**Review by hayajo — APPROVED** [review]
@fujiwara 
Thank you for your contribution!
Please wait for the release.

**Pull request merged**
